import type { Metadata } from "next";
import "@/src/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <aside className="fixed w-[368px] h-full border-r border-r-border">
          <h2>Overview</h2>
          <ul>
            <li></li>
          </ul>
        </aside>
        {children}
      </body>
    </html>
  );
}
